from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_thongtin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_thongtin.setGeometry(QtCore.QRect(70, 100, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_thongtin.setFont(font)
        self.Button_thongtin.setObjectName("Button_thongtin")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Button_danhgia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_danhgia.setGeometry(QtCore.QRect(70, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button_danhgia.setFont(font)
        self.Button_danhgia.setObjectName("Button_danhgia")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 90, 911, 471))
        self.widget.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.widget.setObjectName("widget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 911, 471))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page)
        self.label_4.setGeometry(QtCore.QRect(70, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.page)
        self.label_5.setGeometry(QtCore.QRect(70, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.page)
        self.label_6.setGeometry(QtCore.QRect(70, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(70, 290, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(parent=self.page)
        self.label_9.setGeometry(QtCore.QRect(40, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_magv = QtWidgets.QLineEdit(parent=self.page)
        self.line_magv.setGeometry(QtCore.QRect(220, 70, 361, 31))
        self.line_magv.setObjectName("line_magv")
        self.line_masv = QtWidgets.QLineEdit(parent=self.page)
        self.line_masv.setGeometry(QtCore.QRect(220, 110, 361, 31))
        self.line_masv.setObjectName("line_masv")
        self.text_noidung = QtWidgets.QTextEdit(parent=self.page)
        self.text_noidung.setGeometry(QtCore.QRect(220, 150, 361, 91))
        self.text_noidung.setObjectName("text_noidung")
        self.line_diem = QtWidgets.QLineEdit(parent=self.page)
        self.line_diem.setGeometry(QtCore.QRect(220, 250, 361, 31))
        self.line_diem.setObjectName("line_diem")
        self.line_date = QtWidgets.QLineEdit(parent=self.page)
        self.line_date.setGeometry(QtCore.QRect(220, 290, 361, 31))
        self.line_date.setObjectName("line_date")
        self.button_done = QtWidgets.QPushButton(parent=self.page)
        self.button_done.setGeometry(QtCore.QRect(714, 382, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_done.setFont(font)
        self.button_done.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.button_done.setObjectName("button_done")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(80, 40, 801, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(40, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(60, 90, 191, 471))
        self.widget_2.setObjectName("widget_2")

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1200, 600, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(MainWindow.close)

        self.widget_2.raise_()
        self.Button_thongtin.raise_()
        self.label.raise_()
        self.Button_danhgia.raise_()
        self.widget.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuTh_ng_tin_sinh_vi_n = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuTh_ng_tin_sinh_vi_n.setFont(font)
        self.menuTh_ng_tin_sinh_vi_n.setObjectName("")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuTh_ng_tin_sinh_vi_n.addSeparator()
        self.menubar.addAction(self.menuTh_ng_tin_sinh_vi_n.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect buttons to switch pages
        self.Button_thongtin.clicked.connect(self.show_thongtin)
        self.Button_danhgia.clicked.connect(self.show_danhgia)
        self.button_done.clicked.connect(self.danh_gia)
        self.show_thongtin()

    def hien_thi_thong_tin(self):
        with open('HienThi.txt', 'r') as f:
            masv = f.read().strip()

        conn = sqlite3.connect('qlgv.db')
        cursor = conn.cursor()

        # Lấy dữ liệu từ database
        cursor.execute(
            """SELECT * 
               FROM SinhVien 
               WHERE MaSV = ? """, (masv,))

        rows = cursor.fetchall()


        self.tableWidget.setRowCount(0)  
        for row, form in enumerate(rows):
            self.tableWidget.insertRow(row)
            for column, item in enumerate(form):
                self.tableWidget.setItem(row, column, QtWidgets.QTableWidgetItem(str(item)))


        conn.close()

    def show_thongtin(self):
        self.stackedWidget.setCurrentIndex(1)
        self.hien_thi_thong_tin()

    def show_danhgia(self):
        self.stackedWidget.setCurrentIndex(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_thongtin.setText(_translate("MainWindow", "Thông tin cá nhân"))
        self.label.setText(_translate("MainWindow", "Trang chủ sinh viên"))
        self.Button_danhgia.setText(_translate("MainWindow", "Đánh giá giảng viên"))
        self.label_3.setText(_translate("MainWindow", "Mã giảng viên:"))
        self.label_4.setText(_translate("MainWindow", "Mã sinh viên:"))
        self.label_5.setText(_translate("MainWindow", "Nội dung:"))
        self.label_6.setText(_translate("MainWindow", "Điểm số:"))
        self.label_7.setText(_translate("MainWindow", "Ngày đánh giá:"))
        self.label_9.setText(_translate("MainWindow", "Đánh giá giảng viên"))
        self.button_done.setText(_translate("MainWindow", "Đánh giá"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã SV"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Họ tên"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày sinh"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Giới tính"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Địa chỉ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SĐT"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Mã Lớp"))
        self.label_2.setText(_translate("MainWindow", "Thông tin sinh viên"))
        self.pushButton.setText(_translate("MainWindow", "Thoát"))
        self.menuTh_ng_tin_sinh_vi_n.setTitle(_translate("MainWindow", "Thông tin sinh viên"))

    def danh_gia(self):
        magv = self.line_magv.text()
        masv = self.line_masv.text()
        noidung = self.text_noidung.toPlainText()
        diemso = self.line_diem.text()
        ngaydanhgia = self.line_date.text()

        conn = sqlite3.connect('qlgv.db')
        cursor = conn.cursor()

        query = '''
                INSERT INTO DanhGia (MaGV, MaSV, NoiDung, DiemSo, NgayDanhGia)
                VALUES (?, ?, ?, ?, ?)
                '''
        
        cursor.execute(query, (magv, masv, noidung, diemso, ngaydanhgia))

        conn.commit()
        conn.close()

        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
        msg.setText("Đánh giá đã được lưu thành công!")
        msg.setWindowTitle("Thông báo")
        msg.exec()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec())
